export interface ICocktail {
    idDrink: number;
    strAlcoholic: string;
    strDrink: string;
    strIBA: string;
    strCategory: string;
    strDrinkThumb: string;
    strInstructions: string;
    strInstructionsEn: string;
    strInstructionsIt: string;
    stars?: number;
    strIngredient1?: string;
    strIngredient2?: string;
    strIngredient3?: string;
    strIngredient4?: string;
    strIngredient5?: string;
    strIngredient6?: string;
    strIngredient7?: string;
    strIngredient8?: string;
    strIngredient9?: string;
    strIngredient10?: string;
    strIngredient11?: string;
    strIngredient12?: string;
    strIngredient13?: string;
    strIngredient14?: string;
    strIngredient15?: string;
    favourite?: boolean;
    totStars?: number[];
}
